//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class titizOtoEntities : DbContext
    {
        public titizOtoEntities()
            : base("name=titizOtoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_activation> tbl_activation { get; set; }
        public DbSet<tbl_address> tbl_address { get; set; }
        public DbSet<tbl_adminRole> tbl_adminRole { get; set; }
        public DbSet<tbl_adminUser> tbl_adminUser { get; set; }
        public DbSet<tbl_bank> tbl_bank { get; set; }
        public DbSet<tbl_bankEft> tbl_bankEft { get; set; }
        public DbSet<tbl_bankPos> tbl_bankPos { get; set; }
        public DbSet<tbl_bankPosOption> tbl_bankPosOption { get; set; }
        public DbSet<tbl_brand> tbl_brand { get; set; }
        public DbSet<tbl_business> tbl_business { get; set; }
        public DbSet<tbl_carBrand> tbl_carBrand { get; set; }
        public DbSet<tbl_cargo> tbl_cargo { get; set; }
        public DbSet<tbl_carModel> tbl_carModel { get; set; }
        public DbSet<tbl_carModelProduct> tbl_carModelProduct { get; set; }
        public DbSet<tbl_category> tbl_category { get; set; }
        public DbSet<tbl_critear> tbl_critear { get; set; }
        public DbSet<tbl_discount> tbl_discount { get; set; }
        public DbSet<tbl_email> tbl_email { get; set; }
        public DbSet<tbl_error> tbl_error { get; set; }
        public DbSet<tbl_forgetPassword> tbl_forgetPassword { get; set; }
        public DbSet<tbl_gallery> tbl_gallery { get; set; }
        public DbSet<tbl_module> tbl_module { get; set; }
        public DbSet<tbl_newsletterUser> tbl_newsletterUser { get; set; }
        public DbSet<tbl_openContent> tbl_openContent { get; set; }
        public DbSet<tbl_order> tbl_order { get; set; }
        public DbSet<tbl_orderDetail> tbl_orderDetail { get; set; }
        public DbSet<tbl_page> tbl_page { get; set; }
        public DbSet<tbl_payInfo> tbl_payInfo { get; set; }
        public DbSet<tbl_product> tbl_product { get; set; }
        public DbSet<tbl_productCritear> tbl_productCritear { get; set; }
        public DbSet<tbl_settings> tbl_settings { get; set; }
        public DbSet<tbl_slider> tbl_slider { get; set; }
        public DbSet<tbl_stock> tbl_stock { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<tbl_basket> tbl_basket { get; set; }
        public DbSet<tbl_trackInfo> tbl_trackInfo { get; set; }
    }
}
