//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bankPos
    {
        public tbl_bankPos()
        {
            this.tbl_bankPosOption = new HashSet<tbl_bankPosOption>();
        }
    
        public int bankPosId { get; set; }
        public string name { get; set; }
        public int bankId { get; set; }
        public bool statu { get; set; }
        public bool isMainPos { get; set; }
        public int posTypeId { get; set; }
        public bool isPosShownOnTable { get; set; }
        public string posCode { get; set; }
    
        public virtual tbl_bank tbl_bank { get; set; }
        public virtual ICollection<tbl_bankPosOption> tbl_bankPosOption { get; set; }
    }
}
