//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_critear
    {
        public tbl_critear()
        {
            this.tbl_productCritear = new HashSet<tbl_productCritear>();
        }
    
        public int critearId { get; set; }
        public string name { get; set; }
        public int parentId { get; set; }
        public int sequence { get; set; }
        public bool statu { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual ICollection<tbl_productCritear> tbl_productCritear { get; set; }
    }
}
