//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_adminUser
    {
        public int userId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime enterDate { get; set; }
        public int adminRoleId { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
    
        public virtual tbl_adminRole tbl_adminRole { get; set; }
    }
}
