//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_basket
    {
        public int basketId { get; set; }
        public int productId { get; set; }
        public int quantity { get; set; }
        public string guestCode { get; set; }
        public System.DateTime createTime { get; set; }
        public Nullable<int> userId { get; set; }
        public string optionList { get; set; }
        public string discountCode { get; set; }
    
        public virtual tbl_product tbl_product { get; set; }
    }
}
