//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_settings
    {
        public int settingsId { get; set; }
        public int langId { get; set; }
        public string mailUserName { get; set; }
        public string mailPassword { get; set; }
        public string mailPort { get; set; }
        public string mailSentName { get; set; }
        public string mailSentAddress { get; set; }
        public string mailReceiverAddress { get; set; }
        public string mailSmtpServer { get; set; }
        public string metaDescription { get; set; }
        public string metaDescriptionAdditional { get; set; }
        public string mainPageTitle { get; set; }
        public string allPageTitle { get; set; }
        public string metaKeyword { get; set; }
        public bool registerIsActivationExist { get; set; }
        public bool registerIsThankMessageSend { get; set; }
        public Nullable<bool> mailIsEnableSSL { get; set; }
        public Nullable<bool> isTransferDiscount { get; set; }
        public Nullable<int> transferDiscountType { get; set; }
        public Nullable<decimal> transferDiscountAmount { get; set; }
        public Nullable<bool> isTransferEnable { get; set; }
        public Nullable<bool> isCrediCardEnable { get; set; }
        public string testAccountEmail { get; set; }
        public string testSuccessfulCard { get; set; }
        public string testValidCard { get; set; }
    }
}
