//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_openContent
    {
        public int openContentId { get; set; }
        public int categoryId { get; set; }
        public int langId { get; set; }
        public bool statu { get; set; }
        public int sequence { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
    }
}
