//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_module
    {
        public int moduleId { get; set; }
        public string name { get; set; }
        public string htmlContent { get; set; }
        public string tag { get; set; }
        public int typeId { get; set; }
        public string description { get; set; }
        public int langId { get; set; }
    }
}
