//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public tbl_product()
        {
            this.tbl_carModelProduct = new HashSet<tbl_carModelProduct>();
            this.tbl_gallery = new HashSet<tbl_gallery>();
            this.tbl_basket = new HashSet<tbl_basket>();
            this.tbl_productCritear = new HashSet<tbl_productCritear>();
            this.tbl_stock = new HashSet<tbl_stock>();
        }
    
        public int productId { get; set; }
        public bool isDeleted { get; set; }
        public int brandId { get; set; }
        public int businessId { get; set; }
        public bool statu { get; set; }
        public int sequence { get; set; }
        public decimal price { get; set; }
        public bool isTaxInclude { get; set; }
        public int taxPercent { get; set; }
        public decimal discountPrice { get; set; }
        public bool isDiscountPriceActive { get; set; }
        public string shortDescription { get; set; }
        public string detail { get; set; }
        public string metaKeyword { get; set; }
        public string metaDescription { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public bool isManuelUrl { get; set; }
        public int langId { get; set; }
        public bool isShowCase { get; set; }
    
        public virtual tbl_brand tbl_brand { get; set; }
        public virtual tbl_business tbl_business { get; set; }
        public virtual ICollection<tbl_carModelProduct> tbl_carModelProduct { get; set; }
        public virtual ICollection<tbl_gallery> tbl_gallery { get; set; }
        public virtual ICollection<tbl_basket> tbl_basket { get; set; }
        public virtual ICollection<tbl_productCritear> tbl_productCritear { get; set; }
        public virtual ICollection<tbl_stock> tbl_stock { get; set; }
    }
}
