//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cargo
    {
        public int cargoId { get; set; }
        public decimal price { get; set; }
        public decimal freeCargoPrice { get; set; }
        public string photo { get; set; }
        public string photoCoordinate { get; set; }
        public string name { get; set; }
        public bool statu { get; set; }
        public string detail { get; set; }
        public int sequence { get; set; }
        public int langId { get; set; }
        public bool isCargoPriceOnCustomer { get; set; }
        public string trackUrl { get; set; }
    }
}
