//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_carModel
    {
        public tbl_carModel()
        {
            this.tbl_carModelProduct = new HashSet<tbl_carModelProduct>();
        }
    
        public int carModelId { get; set; }
        public int carBrandId { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public bool statu { get; set; }
        public int sequence { get; set; }
        public bool isManuelUrl { get; set; }
        public int langId { get; set; }
        public string metaKeyword { get; set; }
        public string metaDescription { get; set; }
        public string title { get; set; }
    
        public virtual tbl_carBrand tbl_carBrand { get; set; }
        public virtual ICollection<tbl_carModelProduct> tbl_carModelProduct { get; set; }
    }
}
