//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_discount
    {
        public int discountId { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public int typeId { get; set; }
        public decimal amountPercent { get; set; }
        public decimal minBasketAmount { get; set; }
        public int minBasketCount { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int userId { get; set; }
        public string productList { get; set; }
        public bool isOtherCombine { get; set; }
        public bool statu { get; set; }
        public int repTime { get; set; }
        public bool isManuelGenerated { get; set; }
        public string exculudeProductList { get; set; }
    }
}
