//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_address
    {
        public int addressId { get; set; }
        public string name { get; set; }
        public bool isPersonal { get; set; }
        public int userId { get; set; }
        public bool statu { get; set; }
        public string tcNo { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string postCode { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string companyName { get; set; }
        public string taxOffice { get; set; }
        public string taxNo { get; set; }
        public string deliverPerson { get; set; }
        public int sequence { get; set; }
        public bool isGuestUser { get; set; }
    }
}
