//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_page
    {
        public int pageId { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public int langId { get; set; }
        public string title { get; set; }
        public string metaKeyword { get; set; }
        public string metaDescription { get; set; }
        public int categoryId { get; set; }
        public int sequence { get; set; }
        public bool statu { get; set; }
        public int pageTypeId { get; set; }
        public string redirectPageUrl { get; set; }
        public bool isManuelUrl { get; set; }
        public string detail { get; set; }
        public bool isHelperUrl { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
    }
}
