//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orderDetail
    {
        public int orderDetailId { get; set; }
        public int productId { get; set; }
        public int quantity { get; set; }
        public decimal productPrice { get; set; }
        public int orderId { get; set; }
        public string optionList { get; set; }
        public decimal productTotalPrice { get; set; }
        public string nameWithOption { get; set; }
        public string photo { get; set; }
    }
}
