//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int orderId { get; set; }
        public string orderNo { get; set; }
        public int cargoId { get; set; }
        public int userId { get; set; }
        public int trackInfoId { get; set; }
        public int deliveryAddressId { get; set; }
        public int billingAddressId { get; set; }
        public int paymentTypeId { get; set; }
        public decimal cargoPrice { get; set; }
        public int orderStatu { get; set; }
        public int orderMailStatu { get; set; }
        public decimal totalProductPrice { get; set; }
        public string discountCode { get; set; }
        public decimal discountAmount { get; set; }
        public decimal transferDiscount { get; set; }
        public decimal additionalPrice { get; set; }
        public decimal totalCheckoutPrice { get; set; }
        public int creditPaymentCount { get; set; }
        public bool isRegisteredOrder { get; set; }
        public System.DateTime createDate { get; set; }
        public string salesAgreement { get; set; }
        public string preSalesAgreement { get; set; }
        public string orderGuid { get; set; }
        public int eftId { get; set; }
        public string orderNote { get; set; }
        public bool isCargoOnCustomer { get; set; }
        public string deliveryAddressObj { get; set; }
        public string billingAddressObj { get; set; }
        public string shipmentNo { get; set; }
    }
}
