//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_newsletterUser
    {
        public int newsletterUserId { get; set; }
        public string email { get; set; }
        public string ipNo { get; set; }
        public System.DateTime createTime { get; set; }
    }
}
