//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bankPosOption
    {
        public int bankPosOptionId { get; set; }
        public int paymentCount { get; set; }
        public decimal minBasketAmount { get; set; }
        public decimal additionalAmount { get; set; }
        public bool statu { get; set; }
        public int bankPosId { get; set; }
    
        public virtual tbl_bankPos tbl_bankPos { get; set; }
    }
}
