//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_adminRole
    {
        public tbl_adminRole()
        {
            this.tbl_adminUser = new HashSet<tbl_adminUser>();
        }
    
        public int roleId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tbl_adminUser> tbl_adminUser { get; set; }
    }
}
