//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titizOto.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("titizOto.App_GlobalResources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Bilgileri.
        /// </summary>
        public static string accountAddres {
            get {
                return ResourceManager.GetString("accountAddres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Siprariş.
        /// </summary>
        public static string accountOrder {
            get {
                return ResourceManager.GetString("accountOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivasyonunuz sistemle eşleşmedi.&lt;a href=&quot;[resendLink]&quot; class=&quot;underLine&quot;&gt;Yeni aktivasyon üretmek için tıklayınız.&lt;/a&gt;.
        /// </summary>
        public static string activationCodeError {
            get {
                return ResourceManager.GetString("activationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivasyonun başarıyla tamamlandı.Üye olduğunuz için teşekkür ederiz.&lt;a class=&quot;underLine&quot; href=&quot;/&quot;&gt;Anasayfaya gitmek için tıklayınız&lt;/a&gt;.
        /// </summary>
        public static string activationCodeSucess {
            get {
                return ResourceManager.GetString("activationCodeSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [email] adresine tanımlı bir kullanıcı mevcut.Şifrenizi unuttuysanız , &lt;a class=&quot;underLine&quot;  href=&quot;[forgetPasswordUrl]&quot;&gt; şifremi unuttum &lt;/a&gt; sayfasından şifrenizi yenileyebilirisiniz..
        /// </summary>
        public static string activationHasRegisteredUser {
            get {
                return ResourceManager.GetString("activationHasRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;resentLink&quot;&gt;&lt;a href=&quot;[resentMailLink]&quot; &gt;Mail ulaşmadı,tekrar gönder&lt;/a&gt;&lt;div&gt;Lütfen junk/bulk/spam/önemsiz e-posta gibi istenmeyen e-postaların bulunduğu klasörleri kontrol ediniz.&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        public static string activationMailResend {
            get {
                return ResourceManager.GetString("activationMailResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [email] adresinize aktivasyon maili gönderildi.&lt;br /&gt; Maildeki aktivasyon adresine tıkladığınızda üyeliğiniz oluşacaktır.Teşekkür ederiz.&lt;br /&gt; .
        /// </summary>
        public static string activationMailSend {
            get {
                return ResourceManager.GetString("activationMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [email] adresindeki aktivasyon emailiniz onaylanmamış.Maili tekrar göndermek için : &lt;a class=&quot;underLine&quot; href=&quot;[activationResent]&quot;&gt; Tekrar aktivasyon maili gönder &lt;/a&gt;.
        /// </summary>
        public static string activationNoApprove {
            get {
                return ResourceManager.GetString("activationNoApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemde aktivasyon bekleyen kaydınız bulunamadı.Lütfen &lt;a href=&quot;[registerPage]&quot; class=&quot;underLine&quot;&gt;üyelik sayfasından&lt;/a&gt; yeni üyelik oluşturunuz..
        /// </summary>
        public static string activationResentMailErrorNoUser {
            get {
                return ResourceManager.GetString("activationResentMailErrorNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivasyon maili başarıyla gönderildi..
        /// </summary>
        public static string activationResentSuccess {
            get {
                return ResourceManager.GetString("activationResentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktif.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Ekleme.
        /// </summary>
        public static string addAddress {
            get {
                return ResourceManager.GetString("addAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün satıştan kaldırılmıştır..
        /// </summary>
        public static string addBasketStatu {
            get {
                return ResourceManager.GetString("addBasketStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünün stoğu tükenmiştir..
        /// </summary>
        public static string addBasketStockError {
            get {
                return ResourceManager.GetString("addBasketStockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün sepetinize eklendi..
        /// </summary>
        public static string addBasketSuccess {
            get {
                return ResourceManager.GetString("addBasketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vade Farkı.
        /// </summary>
        public static string additionalPrice {
            get {
                return ResourceManager.GetString("additionalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresiniz başarıyla hesabınıza eklendi..
        /// </summary>
        public static string addressAddSuccess {
            get {
                return ResourceManager.GetString("addressAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string addressCity {
            get {
                return ResourceManager.GetString("addressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir girişi gerekli..
        /// </summary>
        public static string addressCityRequired {
            get {
                return ResourceManager.GetString("addressCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Adı.
        /// </summary>
        public static string addressCompanyName {
            get {
                return ResourceManager.GetString("addressCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şireket Adı girişi gerekli..
        /// </summary>
        public static string addressCompanyNameRequired {
            get {
                return ResourceManager.GetString("addressCompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı İsim Soyisim.
        /// </summary>
        public static string addressDeliveredPerson {
            get {
                return ResourceManager.GetString("addressDeliveredPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı İsim Soyisim girişi gerekli..
        /// </summary>
        public static string addressDeliveredPersonRequired {
            get {
                return ResourceManager.GetString("addressDeliveredPersonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Detayı.
        /// </summary>
        public static string addressDetail {
            get {
                return ResourceManager.GetString("addressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string addressDistrict {
            get {
                return ResourceManager.GetString("addressDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe girişi gerekli..
        /// </summary>
        public static string addressDistrictRequired {
            get {
                return ResourceManager.GetString("addressDistrictRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresiniz başarıyla güncellendi..
        /// </summary>
        public static string addressEditSuccess {
            get {
                return ResourceManager.GetString("addressEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Tanımı ( Ör: Ev,İşyeri.. ).
        /// </summary>
        public static string addressName {
            get {
                return ResourceManager.GetString("addressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Tanımı girişi gerekli..
        /// </summary>
        public static string addressNameRequired {
            get {
                return ResourceManager.GetString("addressNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string addressPhone {
            get {
                return ResourceManager.GetString("addressPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon girişi gerekli..
        /// </summary>
        public static string addressPhoneRequired {
            get {
                return ResourceManager.GetString("addressPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu.
        /// </summary>
        public static string addressPostCode {
            get {
                return ResourceManager.GetString("addressPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu girişi gerekli..
        /// </summary>
        public static string addressPostCodeRequired {
            get {
                return ResourceManager.GetString("addressPostCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres girişi gerekli..
        /// </summary>
        public static string addressRequired {
            get {
                return ResourceManager.GetString("addressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Numarası.
        /// </summary>
        public static string addressTaxNo {
            get {
                return ResourceManager.GetString("addressTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Numarası girişi gerekli..
        /// </summary>
        public static string addressTaxNoRequired {
            get {
                return ResourceManager.GetString("addressTaxNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Dairesi.
        /// </summary>
        public static string addressTaxOffice {
            get {
                return ResourceManager.GetString("addressTaxOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Dairesi girişi gerekli..
        /// </summary>
        public static string addressTaxOfficeRequired {
            get {
                return ResourceManager.GetString("addressTaxOfficeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tc Kimlik No.
        /// </summary>
        public static string addressTcNo {
            get {
                return ResourceManager.GetString("addressTcNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tc Kimlik No girişi gerekli..
        /// </summary>
        public static string addressTcNoRequired {
            get {
                return ResourceManager.GetString("addressTcNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Tipi.
        /// </summary>
        public static string addressType {
            get {
                return ResourceManager.GetString("addressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Tipi girişi gerekli..
        /// </summary>
        public static string addressTypeRequired {
            get {
                return ResourceManager.GetString("addressTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm.
        /// </summary>
        public static string allBrandSee {
            get {
                return ResourceManager.GetString("allBrandSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string allBrandSeeUrl {
            get {
                return ResourceManager.GetString("allBrandSeeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Tutarı.
        /// </summary>
        public static string allPrice {
            get {
                return ResourceManager.GetString("allPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişi Tamamla.
        /// </summary>
        public static string basketCheckout {
            get {
                return ResourceManager.GetString("basketCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişe Devam Et.
        /// </summary>
        public static string basketContinueShopping {
            get {
                return ResourceManager.GetString("basketContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetiniz boş, 
        ///biraz alışverişe ne dersiniz ?.
        /// </summary>
        public static string basketEmtyText1 {
            get {
                return ResourceManager.GetString("basketEmtyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş vermek için dilediğiniz ürünü/ürünleri sepetinize ekleyin.
        ///Sepete eklediğiniz ürünler, sipariş vermediğiniz veya
        ///silmediğiniz sürece sepetinizde kalır..
        /// </summary>
        public static string basketEmtyText2 {
            get {
                return ResourceManager.GetString("basketEmtyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün adet girişini kontrol ediniz..
        /// </summary>
        public static string basketErrorQuantity {
            get {
                return ResourceManager.GetString("basketErrorQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim kuponu başarıyla eklendi..
        /// </summary>
        public static string basketSuccessAddDiscount {
            get {
                return ResourceManager.GetString("basketSuccessAddDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim kuponunuz kaldırıldı..
        /// </summary>
        public static string basketSuccessDeleteDiscount {
            get {
                return ResourceManager.GetString("basketSuccessDeleteDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetinizdeki ürün kaldırıldı..
        /// </summary>
        public static string basketSuccessDeleteItem {
            get {
                return ResourceManager.GetString("basketSuccessDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarıyla gerçekleşti..
        /// </summary>
        public static string basketSuccessOperation {
            get {
                return ResourceManager.GetString("basketSuccessOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetinizdeki ürün güncellendi..
        /// </summary>
        public static string basketSuccessUpdateProduct {
            get {
                return ResourceManager.GetString("basketSuccessUpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepeti Güncelle.
        /// </summary>
        public static string basketUpdate {
            get {
                return ResourceManager.GetString("basketUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Adresi.
        /// </summary>
        public static string billingAddress {
            get {
                return ResourceManager.GetString("billingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        public static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo ücreti.
        /// </summary>
        public static string cargoPrice {
            get {
                return ResourceManager.GetString("cargoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo Takip .
        /// </summary>
        public static string cargoTrack {
            get {
                return ResourceManager.GetString("cargoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Bilgileri.
        /// </summary>
        public static string checkoutAddressInfo {
            get {
                return ResourceManager.GetString("checkoutAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura adresi seçimi gerekli..
        /// </summary>
        public static string checkoutBillingRequired {
            get {
                return ResourceManager.GetString("checkoutBillingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kart No.
        /// </summary>
        public static string checkoutCardInfoCreditCard {
            get {
                return ResourceManager.GetString("checkoutCardInfoCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kart No girişi yapınız..
        /// </summary>
        public static string checkoutCardInfoCreditCardRequired {
            get {
                return ResourceManager.GetString("checkoutCardInfoCreditCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu.
        /// </summary>
        public static string checkoutCardInfoCvv {
            get {
                return ResourceManager.GetString("checkoutCardInfoCvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu nedir ? .
        /// </summary>
        public static string checkoutCardInfoCvvAbout {
            get {
                return ResourceManager.GetString("checkoutCardInfoCvvAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu girişi yapınız..
        /// </summary>
        public static string checkoutCardInfoCvvRequired {
            get {
                return ResourceManager.GetString("checkoutCardInfoCvvRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Kullanma Tarihi.
        /// </summary>
        public static string checkoutCardInfoLastUse {
            get {
                return ResourceManager.GetString("checkoutCardInfoLastUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Üzerindeki İsim.
        /// </summary>
        public static string checkoutCardName {
            get {
                return ResourceManager.GetString("checkoutCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Üzerindeki İsim gereklidir..
        /// </summary>
        public static string checkoutCardNameRequired {
            get {
                return ResourceManager.GetString("checkoutCardNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek çekim veya taksit seçimi yapınız..
        /// </summary>
        public static string checkoutCardOptionRequired {
            get {
                return ResourceManager.GetString("checkoutCardOptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo Bedava.
        /// </summary>
        public static string checkoutCargoFree {
            get {
                return ResourceManager.GetString("checkoutCargoFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo ücreti alıcıya ait..
        /// </summary>
        public static string checkoutCargoOnCustomer {
            get {
                return ResourceManager.GetString("checkoutCargoOnCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo seçimi yapınız..
        /// </summary>
        public static string checkoutCargoRequired {
            get {
                return ResourceManager.GetString("checkoutCargoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek çekim.
        /// </summary>
        public static string checkoutCash {
            get {
                return ResourceManager.GetString("checkoutCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string checkoutChange {
            get {
                return ResourceManager.GetString("checkoutChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam Et.
        /// </summary>
        public static string checkoutContinue {
            get {
                return ResourceManager.GetString("checkoutContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kartı.
        /// </summary>
        public static string checkoutCrediCard {
            get {
                return ResourceManager.GetString("checkoutCrediCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İster tek çekim, ister taksitli alışveriş seçeneği ile ödeme yapabilirsiniz..
        /// </summary>
        public static string checkoutCrediCardDetail {
            get {
                return ResourceManager.GetString("checkoutCrediCardDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi kartı numarasını boşluk bırakmadan giriniz..
        /// </summary>
        public static string checkoutCreditInfoNoSpace {
            get {
                return ResourceManager.GetString("checkoutCreditInfoNoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme seçenekleri.
        /// </summary>
        public static string checkoutCreditInfoOptionList {
            get {
                return ResourceManager.GetString("checkoutCreditInfoOptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçenekler getirilemiyor.Hata raporlandı.Lütfen tekrar deneyiniz..
        /// </summary>
        public static string checkoutCreditInfoOptionListError {
            get {
                return ResourceManager.GetString("checkoutCreditInfoOptionListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme seçeneklerini görmek için kredi kartı no girişi yapınız..
        /// </summary>
        public static string checkoutCreditInfoOptionListNoOption {
            get {
                return ResourceManager.GetString("checkoutCreditInfoOptionListNoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit tablosu.
        /// </summary>
        public static string checkoutCreditInfoOptionTable {
            get {
                return ResourceManager.GetString("checkoutCreditInfoOptionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslimat adresi seçimi gerekli..
        /// </summary>
        public static string checkoutDeliveryRequired {
            get {
                return ResourceManager.GetString("checkoutDeliveryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura adresi de aynı olsun.
        /// </summary>
        public static string checkoutDeliverySameAddress {
            get {
                return ResourceManager.GetString("checkoutDeliverySameAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Takip Bilgileri.
        /// </summary>
        public static string checkoutDeliveryTrackInfo {
            get {
                return ResourceManager.GetString("checkoutDeliveryTrackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit.
        /// </summary>
        public static string checkoutInstallment {
            get {
                return ResourceManager.GetString("checkoutInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL ve üzeri.
        /// </summary>
        public static string checkoutInstallmentSpentRequired {
            get {
                return ResourceManager.GetString("checkoutInstallmentSpentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye olmadan ödemeyi tamamla.
        /// </summary>
        public static string checkoutRegisterStatuGuest {
            get {
                return ResourceManager.GetString("checkoutRegisterStatuGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye ol veya giriş yap.
        /// </summary>
        public static string checkoutRegisterStatuRegisterOrLogin {
            get {
                return ResourceManager.GetString("checkoutRegisterStatuRegisterOrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam etmek için kayıt seçeneğini seçiniz..
        /// </summary>
        public static string checkoutRegisterStatuRequired {
            get {
                return ResourceManager.GetString("checkoutRegisterStatuRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Aşamaları.
        /// </summary>
        public static string checkoutRightStepTitle {
            get {
                return ResourceManager.GetString("checkoutRightStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havale.
        /// </summary>
        public static string checkoutTransfer {
            get {
                return ResourceManager.GetString("checkoutTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçeceğiniz banka hesabına havale yaparak ödeme yapabilirsiniz..
        /// </summary>
        public static string checkoutTransferDetail {
            get {
                return ResourceManager.GetString("checkoutTransferDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Extra [amount] indirim).
        /// </summary>
        public static string checkoutTransferDiscount {
            get {
                return ResourceManager.GetString("checkoutTransferDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçim.
        /// </summary>
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişi Tamamla.
        /// </summary>
        public static string completeOrder {
            get {
                return ResourceManager.GetString("completeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        public static string corporate {
            get {
                return ResourceManager.GetString("corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Silme.
        /// </summary>
        public static string deleteAddress {
            get {
                return ResourceManager.GetString("deleteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresiniz başarıyla silindi..
        /// </summary>
        public static string deleteAddressSuccess {
            get {
                return ResourceManager.GetString("deleteAddressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslimat Adresi.
        /// </summary>
        public static string deliveryAddress {
            get {
                return ResourceManager.GetString("deliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        public static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detayı Görüntüle.
        /// </summary>
        public static string detailSee {
            get {
                return ResourceManager.GetString("detailSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim Kuponu.
        /// </summary>
        public static string discountCupon {
            get {
                return ResourceManager.GetString("discountCupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim kuponu sepetinizde bulunmaktadır..
        /// </summary>
        public static string discountErrorAlreadyUse {
            get {
                return ResourceManager.GetString("discountErrorAlreadyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim kuponu minimum ürün sayısını karşılamamaktadır..
        /// </summary>
        public static string discountErrorMinCount {
            get {
                return ResourceManager.GetString("discountErrorMinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim kuponu minimum sepet tutarını karşılamamaktadır..
        /// </summary>
        public static string discountErrorMinSpent {
            get {
                return ResourceManager.GetString("discountErrorMinSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim kuponu sistemde bulunamadı..
        /// </summary>
        public static string discountErrorNotFoundInSystem {
            get {
                return ResourceManager.GetString("discountErrorNotFoundInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim kuponu sepetinizdeki ürün / ürünleri kapsamamaktadır..
        /// </summary>
        public static string discountErrorProduct {
            get {
                return ResourceManager.GetString("discountErrorProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim kuponu tekrarlanma sayısı dolmuştur..
        /// </summary>
        public static string discountErrorRepTime {
            get {
                return ResourceManager.GetString("discountErrorRepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim kuponu kişiye özel tanımlıdır.Üye girişi yaptıktan sonra kuponu eklemeniz gerekmektedir..
        /// </summary>
        public static string discountErrorUser {
            get {
                return ResourceManager.GetString("discountErrorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuponunuz başarıyla eklendi..
        /// </summary>
        public static string discountSuccess {
            get {
                return ResourceManager.GetString("discountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Düzenle.
        /// </summary>
        public static string editAddress {
            get {
                return ResourceManager.GetString("editAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap No.
        /// </summary>
        public static string eftAccountNo {
            get {
                return ResourceManager.GetString("eftAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube Kodu.
        /// </summary>
        public static string eftBranchCode {
            get {
                return ResourceManager.GetString("eftBranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iban.
        /// </summary>
        public static string eftIban {
            get {
                return ResourceManager.GetString("eftIban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havale Id.
        /// </summary>
        public static string eftId {
            get {
                return ResourceManager.GetString("eftId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havale seçimi yapınız..
        /// </summary>
        public static string eftIdRequried {
            get {
                return ResourceManager.GetString("eftIdRequried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Adı.
        /// </summary>
        public static string eftName {
            get {
                return ResourceManager.GetString("eftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string emailName {
            get {
                return ResourceManager.GetString("emailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail alanı gerekli..
        /// </summary>
        public static string emailRequired {
            get {
                return ResourceManager.GetString("emailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemde kayıtlı mailiniz bulunamadı..
        /// </summary>
        public static string forgetPasswordError {
            get {
                return ResourceManager.GetString("forgetPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [email] adresinize şifre sıfırlama maili gönderildi.Maildeki adrese tıklayarak şifrenizi yenileyebilirsiniz..
        /// </summary>
        public static string forgetPasswordSuccess {
            get {
                return ResourceManager.GetString("forgetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string formBirthday {
            get {
                return ResourceManager.GetString("formBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün.
        /// </summary>
        public static string formDay {
            get {
                return ResourceManager.GetString("formDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün seçimi yapınız..
        /// </summary>
        public static string formDayRequired {
            get {
                return ResourceManager.GetString("formDayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string formEmail {
            get {
                return ResourceManager.GetString("formEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail girişi yapınız..
        /// </summary>
        public static string formEmailRequired {
            get {
                return ResourceManager.GetString("formEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        public static string formGender {
            get {
                return ResourceManager.GetString("formGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet seçimi yapınız..
        /// </summary>
        public static string formGenderRequired {
            get {
                return ResourceManager.GetString("formGenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkek.
        /// </summary>
        public static string formMen {
            get {
                return ResourceManager.GetString("formMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ay.
        /// </summary>
        public static string formMonth {
            get {
                return ResourceManager.GetString("formMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ay seçimi yapınız..
        /// </summary>
        public static string formMonthRequired {
            get {
                return ResourceManager.GetString("formMonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string formName {
            get {
                return ResourceManager.GetString("formName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad girişi yapınız..
        /// </summary>
        public static string formNameRequired {
            get {
                return ResourceManager.GetString("formNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz.
        /// </summary>
        public static string formPassword {
            get {
                return ResourceManager.GetString("formPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre girişi yapınız..
        /// </summary>
        public static string formPasswordRequired {
            get {
                return ResourceManager.GetString("formPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrarı.
        /// </summary>
        public static string formPassworRep {
            get {
                return ResourceManager.GetString("formPassworRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrarı girişi yapınız..
        /// </summary>
        public static string formPassworRepRequired {
            get {
                return ResourceManager.GetString("formPassworRepRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre tekrarınız uyuşmamaktadır..
        /// </summary>
        public static string formPassworRepSame {
            get {
                return ResourceManager.GetString("formPassworRepSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız.
        /// </summary>
        public static string formSurname {
            get {
                return ResourceManager.GetString("formSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad girişi yapınız..
        /// </summary>
        public static string formSurnameRequired {
            get {
                return ResourceManager.GetString("formSurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik Sözleşmesi.
        /// </summary>
        public static string formUserDocument {
            get {
                return ResourceManager.GetString("formUserDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;ni okudum, kabul ediyorum..
        /// </summary>
        public static string formUserDocumentRead {
            get {
                return ResourceManager.GetString("formUserDocumentRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik sözleşmesini onaylayınız..
        /// </summary>
        public static string formUserDocumentRequired {
            get {
                return ResourceManager.GetString("formUserDocumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir tarih girişi yapınız..
        /// </summary>
        public static string formValidDate {
            get {
                return ResourceManager.GetString("formValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail adresinizi kontrol ediniz..
        /// </summary>
        public static string formValidEmail {
            get {
                return ResourceManager.GetString("formValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın.
        /// </summary>
        public static string formWomen {
            get {
                return ResourceManager.GetString("formWomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıl.
        /// </summary>
        public static string formYear {
            get {
                return ResourceManager.GetString("formYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıl seçimi yapınız..
        /// </summary>
        public static string formYearRequired {
            get {
                return ResourceManager.GetString("formYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişi Getir.
        /// </summary>
        public static string getOrder {
            get {
                return ResourceManager.GetString("getOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string goBack {
            get {
                return ResourceManager.GetString("goBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişlerime Geri Dön.
        /// </summary>
        public static string goBackOrder {
            get {
                return ResourceManager.GetString("goBackOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit Tutarı.
        /// </summary>
        public static string installmentAmount {
            get {
                return ResourceManager.GetString("installmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit Sayısı.
        /// </summary>
        public static string installmentCount {
            get {
                return ResourceManager.GetString("installmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string langCode {
            get {
                return ResourceManager.GetString("langCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string langId {
            get {
                return ResourceManager.GetString("langId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail girişi yapınız..
        /// </summary>
        public static string loginItemLoginEmailRequired {
            get {
                return ResourceManager.GetString("loginItemLoginEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre girişi yapınız..
        /// </summary>
        public static string loginItemLoginPasswordRequired {
            get {
                return ResourceManager.GetString("loginItemLoginPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook ile Giriş Yap.
        /// </summary>
        public static string loginRegisterPageFacebook {
            get {
                return ResourceManager.GetString("loginRegisterPageFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string loginRegisterPageLogin {
            get {
                return ResourceManager.GetString("loginRegisterPageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string loginRegisterPageRegister {
            get {
                return ResourceManager.GetString("loginRegisterPageRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla giriş yapıldı.Kaldığınız sayfaya yönleniyorsunuz....
        /// </summary>
        public static string loginSuccess {
            get {
                return ResourceManager.GetString("loginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email / Şifre hatalı.
        /// </summary>
        public static string loginUnregisteredOrPassword {
            get {
                return ResourceManager.GetString("loginUnregisteredOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Hatalı.
        /// </summary>
        public static string mailError {
            get {
                return ResourceManager.GetString("mailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresiniz Kayıtlı.
        /// </summary>
        public static string mailExist {
            get {
                return ResourceManager.GetString("mailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string mainPage {
            get {
                return ResourceManager.GetString("mainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeller.
        /// </summary>
        public static string models {
            get {
                return ResourceManager.GetString("models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetim.
        /// </summary>
        public static string myBasket {
            get {
                return ResourceManager.GetString("myBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetim.
        /// </summary>
        public static string myCart {
            get {
                return ResourceManager.GetString("myCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam etmek için giriş yapınız..
        /// </summary>
        public static string needLogin {
            get {
                return ResourceManager.GetString("needLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Adres Ekle.
        /// </summary>
        public static string newAddressAdd {
            get {
                return ResourceManager.GetString("newAddressAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krom Aksesuar Yeni Ürünlerimiz.
        /// </summary>
        public static string newProducts {
            get {
                return ResourceManager.GetString("newProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Bülten.
        /// </summary>
        public static string newsletter {
            get {
                return ResourceManager.GetString("newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Bülten Aboneliği.
        /// </summary>
        public static string newsletterSubscribe {
            get {
                return ResourceManager.GetString("newsletterSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailiniz Başarıyla Kaydedildi.
        /// </summary>
        public static string newsletterSuccessMsg {
            get {
                return ResourceManager.GetString("newsletterSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemde kayıtlı adresiniz bulunmamaktadır..
        /// </summary>
        public static string noAddressFind {
            get {
                return ResourceManager.GetString("noAddressFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemde kayıtlı indirim kuponunuz bulunmamaktadır..
        /// </summary>
        public static string noDiscountFind {
            get {
                return ResourceManager.GetString("noDiscountFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemde kayıtlı siparişiniz bulunmamaktadır..
        /// </summary>
        public static string noOrderFind {
            get {
                return ResourceManager.GetString("noOrderFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ilgili sonuç bulunamamıştır..
        /// </summary>
        public static string noResultFound {
            get {
                return ResourceManager.GetString("noResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme işleminde sepetinizde güncelleme olduğundan tekrar sepet sayfasına yönelendirildiniz.Lütfen ödemeye işlemini tekrar başlatınız..
        /// </summary>
        public static string onCheckoutBasketChange {
            get {
                return ResourceManager.GetString("onCheckoutBasketChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme sistemi ile bağlantı kurulamadı.Hata raporlandı.Lütfen tekrar deneyiniz..
        /// </summary>
        public static string orderErrorOnPayment {
            get {
                return ResourceManager.GetString("orderErrorOnPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş kaydınızda beklenmedik hata meydana geldi.Hata raporlandı.24 saat içersinde yapılan ödeme iptal edilerek sizinle iletişime geçilecektir..
        /// </summary>
        public static string orderErrorOnSaveOrder {
            get {
                return ResourceManager.GetString("orderErrorOnSaveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme alınamadı.Lütfe ödeme bilgilerinizi tekrar kontrol ediniz..
        /// </summary>
        public static string orderErrorPaymentInfoWrong {
            get {
                return ResourceManager.GetString("orderErrorPaymentInfoWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string orderListDate {
            get {
                return ResourceManager.GetString("orderListDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş No.
        /// </summary>
        public static string orderListOrderNo {
            get {
                return ResourceManager.GetString("orderListOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş no girişi gereklidir..
        /// </summary>
        public static string orderListOrderNoRequired {
            get {
                return ResourceManager.GetString("orderListOrderNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string orderListStatu {
            get {
                return ResourceManager.GetString("orderListStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Fiyat.
        /// </summary>
        public static string orderListTotalPrice {
            get {
                return ResourceManager.GetString("orderListTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş no 7 haneli olmalıdır..
        /// </summary>
        public static string orderNoSevenDigit {
            get {
                return ResourceManager.GetString("orderNoSevenDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletmek istediğiniz sipariş notu:.
        /// </summary>
        public static string orderNote {
            get {
                return ResourceManager.GetString("orderNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişiniz bulunamadı.Lütfen email veya sipariş numarasının doğruluğunu kontrol ediniz.Eğer kayıtlı üye olarak siparişinizi verdiyseniz sisteme giriş yapınız..
        /// </summary>
        public static string orderSearchNotFound {
            get {
                return ResourceManager.GetString("orderSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye siparişleri.
        /// </summary>
        public static string orderSearchRigister {
            get {
                return ResourceManager.GetString("orderSearchRigister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye girişi yapınız.
        /// </summary>
        public static string orderSearchToLogin {
            get {
                return ResourceManager.GetString("orderSearchToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye olmadan yapılan sipariş.
        /// </summary>
        public static string orderSearchWithoutRegister {
            get {
                return ResourceManager.GetString("orderSearchWithoutRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string orderStatu {
            get {
                return ResourceManager.GetString("orderStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Onaylandı.
        /// </summary>
        public static string orderStatuApproved {
            get {
                return ResourceManager.GetString("orderStatuApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Edildi.
        /// </summary>
        public static string orderStatuCompleted {
            get {
                return ResourceManager.GetString("orderStatuCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Edildi.
        /// </summary>
        public static string orderStatuDelivered {
            get {
                return ResourceManager.GetString("orderStatuDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarik Ediliyor.
        /// </summary>
        public static string orderStatuLeadTime {
            get {
                return ResourceManager.GetString("orderStatuLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargoya Verildi.
        /// </summary>
        public static string orderStatuOnCargo {
            get {
                return ResourceManager.GetString("orderStatuOnCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazırlanıyor.
        /// </summary>
        public static string orderStatuPreparing {
            get {
                return ResourceManager.GetString("orderStatuPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Bekliyor.
        /// </summary>
        public static string orderStatuWaitPayment {
            get {
                return ResourceManager.GetString("orderStatuWaitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın aldığınız için teşekkür ederiz. Sipariş No #:[order_no]
        ///&lt;br /&gt;
        ///Sipariş detaylarını incelemek için size bir e-posta gönderdik. Siparişinizin bir kopyasını görmek veya yazdırmak için  &lt;a target=&quot;_blank&quot; href=&quot;[orderNoDetail]&quot; rel=&quot;nofollow&quot;&gt; sipariş detayı &lt;/a&gt; görüntüleyiniz..
        /// </summary>
        public static string orderSuccessful {
            get {
                return ResourceManager.GetString("orderSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişiniz ilgili havale bedelini 3 işgünü içinde yatırmamanız halinde iptal edilecektir. Aşağıda seçtiğiniz banka hesap numarasını bulabilirsiniz. Ödemelerinizde sipariş numarasını belirtmeyi lütfen unutmayınız..
        /// </summary>
        public static string orderTransferInfo {
            get {
                return ResourceManager.GetString("orderTransferInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Bilgisi.
        /// </summary>
        public static string orderTransferInfoTitle {
            get {
                return ResourceManager.GetString("orderTransferInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pasif.
        /// </summary>
        public static string passive {
            get {
                return ResourceManager.GetString("passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz en az {2} karakter en çok {1} karakter olmalıdır..
        /// </summary>
        public static string passwordLength {
            get {
                return ResourceManager.GetString("passwordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string passwordName {
            get {
                return ResourceManager.GetString("passwordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Tipi.
        /// </summary>
        public static string paymentType {
            get {
                return ResourceManager.GetString("paymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bireysel.
        /// </summary>
        public static string personal {
            get {
                return ResourceManager.GetString("personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçim Yapınız.
        /// </summary>
        public static string pleaseSelect {
            get {
                return ResourceManager.GetString("pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres seçimi yapınız.
        /// </summary>
        public static string pleaseSelectAddress {
            get {
                return ResourceManager.GetString("pleaseSelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Sipariş Formu.
        /// </summary>
        public static string preSalesAgreement {
            get {
                return ResourceManager.GetString("preSalesAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okudum, onaylıyorum..
        /// </summary>
        public static string preSalesAgreementDetail {
            get {
                return ResourceManager.GetString("preSalesAgreementDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Sipariş Formu onayı gerekli..
        /// </summary>
        public static string preSalesAgreementRequired {
            get {
                return ResourceManager.GetString("preSalesAgreementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürüne ait özellik seçimi yapınız..
        /// </summary>
        public static string productOptionSelect {
            get {
                return ResourceManager.GetString("productOptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        public static string registerInfo {
            get {
                return ResourceManager.GetString("registerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre sıfırlama kodu alınamadı.Lürfen tekrar &lt;a href=&quot;[forgetPasswordLink]&quot; class=&quot;underLine&quot; &gt;Şifremi Unuttum&lt;/a&gt; sayfasından işlem yapınız..
        /// </summary>
        public static string resetPasswordNull {
            get {
                return ResourceManager.GetString("resetPasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz başarıyla değiştirildi.&lt;a href=&quot;[loginPage]&quot; class=&quot;underLine&quot;&gt;Giriş sayfası&apos;dan&lt;/a&gt;  ile yeni şifreniz ile giriş yapabilirsiniz..
        /// </summary>
        public static string resetPasswordSuccess {
            get {
                return ResourceManager.GetString("resetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre sıfırlama kodu doğrulanamadı.Lürfen tekrar &lt;a href=&quot;[forgetPasswordLink]&quot; class=&quot;underLine&quot; &gt;Şifremi Unuttum&lt;/a&gt; sayfasından işlem yapınız..
        /// </summary>
        public static string resetPasswordWrong {
            get {
                return ResourceManager.GetString("resetPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Sözleşmesi.
        /// </summary>
        public static string salesAgreement {
            get {
                return ResourceManager.GetString("salesAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okudum, onaylıyorum..
        /// </summary>
        public static string salesAgreementDetail {
            get {
                return ResourceManager.GetString("salesAgreementDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Sözleşmesi onayı gerekli..
        /// </summary>
        public static string salesAgreementRequired {
            get {
                return ResourceManager.GetString("salesAgreementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet ve Devam et.
        /// </summary>
        public static string saveAndContinue {
            get {
                return ResourceManager.GetString("saveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonuç bulunamadı.Lütfen yeni bir arama yapınız..
        /// </summary>
        public static string searchModalNoResult {
            get {
                return ResourceManager.GetString("searchModalNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam [totalSearch] sonuç&lt;br /&gt; Tümünü görüntüle.
        /// </summary>
        public static string searchModalResult {
            get {
                return ResourceManager.GetString("searchModalResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama yapmak için en az 3 harf giriniz..
        /// </summary>
        public static string searchRequired {
            get {
                return ResourceManager.GetString("searchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasif Yap.
        /// </summary>
        public static string setFalse {
            get {
                return ResourceManager.GetString("setFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Yap.
        /// </summary>
        public static string setTrue {
            get {
                return ResourceManager.GetString("setTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayrıntıları Göster.
        /// </summary>
        public static string showDetail {
            get {
                return ResourceManager.GetString("showDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetinizdeki ürünler maksimum stok miktarına göre güncellenmiştir..
        /// </summary>
        public static string stockAdjust {
            get {
                return ResourceManager.GetString("stockAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string topCartLogin {
            get {
                return ResourceManager.GetString("topCartLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Çıkış Yap).
        /// </summary>
        public static string topCartLogout {
            get {
                return ResourceManager.GetString("topCartLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string topCartRegister {
            get {
                return ResourceManager.GetString("topCartRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam {0} sonuç bulundu..
        /// </summary>
        public static string totalResultFound {
            get {
                return ResourceManager.GetString("totalResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havale İndirimi.
        /// </summary>
        public static string transferDiscount {
            get {
                return ResourceManager.GetString("transferDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklenmedik Hata Meydana Geldi.Lütfen Tekrar Deneyiniz..
        /// </summary>
        public static string unexpectedErrorMsg {
            get {
                return ResourceManager.GetString("unexpectedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz güncellendi..
        /// </summary>
        public static string updatePasswordSuccess {
            get {
                return ResourceManager.GetString("updatePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileriniz güncellendi..
        /// </summary>
        public static string userInfoUpdated {
            get {
                return ResourceManager.GetString("userInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Yapılıyor.
        /// </summary>
        public static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Bülten aboneliğiniz.
        /// </summary>
        public static string yourNewsletter {
            get {
                return ResourceManager.GetString("yourNewsletter", resourceCulture);
            }
        }
    }
}
